conditioning:
  method: 'ps_lin'
  params:
    guidance_start: 0
    guidance_end: 0.4
    # guidance_start_t: 0
    # guidance_end_t: 1000

data:
  name: shapenet15k
  root: ./data/ShapeNetCore.v2.PC15k
  category_to_find: 'chair'
  model_n_points: 8192

measurement:
  operator:
    name: denoise_pcd # denoise, inpainting, super_resolution, blur
  # kernel_size: 61
  # intensity: 0.5

  noise:
    name: song_chamfer
    sigma: 0.05
  
prompt: ""