#================================================================
# Configuration for Inverse Problem Solving using LION
#================================================================

# --- File and Directory Paths ---
paths:
  pcd_data: './data/ShapeNetCore.v2.PC15k'
  model: './lion_ckpt/text2shape/chair/checkpoints/model.pt'
  model_cfg: './config/chair_cfg.yml' # './lion_ckpt/text2shape/chair/cfg.yml'
  log_dir: './log'

# --- Experiment Settings ---
experiment:
  category_to_find: 'chair'
  forward_operator: 'denoise_pcd'
  prompt: ""

# --- Hyperparameters ---
hyperparameters:
  guidance_scale: 200 # 1e-3
  guidance_start_t: 600
  debug_mode: true
  model_n_points: 2048